// Code generated by testkit sentinel. DO NOT EDIT.
// Source: testkit sentinel

package epoch_test

import (
	"errors"
	"strings"
	"testing"

	"go.thesmos.sh/core/epoch"

	"go.thesmos.sh/testkit"
)

func TestEpochSentinelErrors(t *testing.T) {
	t.Parallel()

	type errEntry struct {
		name string
		err  error
	}
	all := []errEntry{
		{"ErrFenced", epoch.ErrFenced},
		{"ErrSize", epoch.ErrSize},
	}

	t.Run("prefix", func(t *testing.T) {
		t.Parallel()
		prefix := "epoch: "
		for _, e := range all {
			t.Run(e.name+" has correct prefix", func(t *testing.T) {
				t.Parallel()
				testkit.True(t, strings.HasPrefix(e.err.Error(), prefix),
					e.name+" must start with "+prefix)
			})
		}
	})

	t.Run("uniqueness", func(t *testing.T) {
		t.Parallel()
		seen := make(map[string]string)
		for _, e := range all {
			msg := e.err.Error()
			other, dup := seen[msg]
			testkit.False(t, dup,
				e.name+" and "+other+" have identical .Error(): "+msg)
			seen[msg] = e.name
		}
	})

	t.Run("non-overlap", func(t *testing.T) {
		t.Parallel()
		for i, a := range all {
			for j, b := range all {
				if i == j {
					continue
				}
				t.Run(a.name+" is not "+b.name, func(t *testing.T) {
					t.Parallel()
					testkit.ErrorIsNot(t, a.err, b.err,
						a.name+" must not match "+b.name)
				})
			}
		}
	})

	t.Run("unwrap chain", func(t *testing.T) {
		t.Parallel()
		for _, e := range all {
			t.Run(e.name+" preserves chain when wrapped", func(t *testing.T) {
				t.Parallel()
				wrapped := errors.Join(e.err, errors.New("extra context"))
				testkit.ErrorIs(t, wrapped, e.err,
					"wrapped "+e.name+" must satisfy errors.Is")
			})
		}
	})
}
