// Code generated by testkit suite. DO NOT EDIT.
// Source: hasher.go:103-166 (testkit suite Hasher)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertHasherContract runs conformance assertions against
// implementations of [crypto.Hasher] produced by factory.
//
//	Default subtests: 9 across 7 methods
//	Shapes detected:  Pure (Algorithm, Combine, CombineTagged, Hash, HashTagged, ID, NewStream)
//	Directives:       none
//	Plug-in points:   HasherOnAlgorithm, HasherOnCombine, HasherOnCombineTagged, HasherOnHash, HasherOnHashTagged, HasherOnID, HasherOnNewStream, HasherOnAll, HasherCustom
func AssertHasherContract(
	t *testing.T,
	factory func() crypto.Hasher,
	opts ...HasherOption,
) {
	t.Helper()
	cfg := newHasherConfig(opts...)

	runHasherAlgorithm(t, factory, &cfg)
	runHasherCombine(t, factory, &cfg)
	runHasherCombineTagged(t, factory, &cfg)
	runHasherHash(t, factory, &cfg)
	runHasherHashTagged(t, factory, &cfg)
	runHasherID(t, factory, &cfg)
	runHasherNewStream(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[crypto.Hasher]{
			T:             t,
			CrossBindings: bindings.CrossBindings[crypto.Hasher]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runHasherAlgorithm(t *testing.T, factory func() crypto.Hasher, cfg *hasherConfig) {
	t.Helper()

	t.Run("Algorithm/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Algorithm panicked on zero-value args (%v) — supply sample values via HasherOnAlgorithm", r)
			}
		}()
		s := factory()
		_ = s.Algorithm()
	})
	if len(cfg.onAlgorithm) > 0 {
		t.Run("Algorithm", func(t *testing.T) {
			prePopFactory := func() crypto.Hasher {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Hasher, crypto.Algorithm]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Hasher, crypto.Algorithm]{
					Factory: prePopFactory,
					Call: func(impl crypto.Hasher) crypto.Algorithm {
						return impl.Algorithm()
					},
				},
			}
			for _, a := range cfg.onAlgorithm {
				a(pctx)
			}
		})
	}
}

func runHasherCombine(t *testing.T, factory func() crypto.Hasher, cfg *hasherConfig) {
	t.Helper()

	t.Run("Combine/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Combine panicked on zero-value args (%v) — supply sample values via HasherOnCombine", r)
			}
		}()
		s := factory()
		_ = s.Combine(SampleDigest(s), SampleDigest(s))
	})
	if len(cfg.onCombine) > 0 {
		t.Run("Combine", func(t *testing.T) {
			prePopFactory := func() crypto.Hasher {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Hasher, crypto.Digest]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Hasher, crypto.Digest]{
					Factory: prePopFactory,
					Call: func(impl crypto.Hasher) crypto.Digest {
						return impl.Combine(SampleDigest(impl), SampleDigest(impl))
					},
				},
			}
			for _, a := range cfg.onCombine {
				a(pctx)
			}
		})
	}
}

func runHasherCombineTagged(t *testing.T, factory func() crypto.Hasher, cfg *hasherConfig) {
	t.Helper()

	t.Run("CombineTagged/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: CombineTagged panicked on zero-value args (%v) — supply sample values via HasherOnCombineTagged", r)
			}
		}()
		s := factory()
		_ = s.CombineTagged(SampleBinaryRole(s), SampleDigest(s), SampleDigest(s))
	})
	if len(cfg.onCombineTagged) > 0 {
		t.Run("CombineTagged", func(t *testing.T) {
			prePopFactory := func() crypto.Hasher {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Hasher, crypto.Digest]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Hasher, crypto.Digest]{
					Factory: prePopFactory,
					Call: func(impl crypto.Hasher) crypto.Digest {
						return impl.CombineTagged(SampleBinaryRole(impl), SampleDigest(impl), SampleDigest(impl))
					},
				},
			}
			for _, a := range cfg.onCombineTagged {
				a(pctx)
			}
		})
	}
}

func runHasherHash(t *testing.T, factory func() crypto.Hasher, cfg *hasherConfig) {
	t.Helper()

	t.Run("Hash/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Hash panicked on zero-value args (%v) — supply sample values via HasherOnHash", r)
			}
		}()
		s := factory()
		_ = s.Hash(nil)
	})

	t.Run("Hash/nil data", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().Hash(nil)
		})
	})
	if len(cfg.onHash) > 0 {
		t.Run("Hash", func(t *testing.T) {
			prePopFactory := func() crypto.Hasher {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Hasher, crypto.Digest]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Hasher, crypto.Digest]{
					Factory: prePopFactory,
					Call: func(impl crypto.Hasher) crypto.Digest {
						return impl.Hash(nil)
					},
				},
			}
			for _, a := range cfg.onHash {
				a(pctx)
			}
		})
	}
}

func runHasherHashTagged(t *testing.T, factory func() crypto.Hasher, cfg *hasherConfig) {
	t.Helper()

	t.Run("HashTagged/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: HashTagged panicked on zero-value args (%v) — supply sample values via HasherOnHashTagged", r)
			}
		}()
		s := factory()
		_ = s.HashTagged(SampleUnaryRole(s), SampleBytes(s))
	})

	t.Run("HashTagged/nil data", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().HashTagged(0, nil)
		})
	})
	if len(cfg.onHashTagged) > 0 {
		t.Run("HashTagged", func(t *testing.T) {
			prePopFactory := func() crypto.Hasher {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Hasher, crypto.Digest]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Hasher, crypto.Digest]{
					Factory: prePopFactory,
					Call: func(impl crypto.Hasher) crypto.Digest {
						return impl.HashTagged(SampleUnaryRole(impl), SampleBytes(impl))
					},
				},
			}
			for _, a := range cfg.onHashTagged {
				a(pctx)
			}
		})
	}
}

func runHasherID(t *testing.T, factory func() crypto.Hasher, cfg *hasherConfig) {
	t.Helper()

	t.Run("ID/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: ID panicked on zero-value args (%v) — supply sample values via HasherOnID", r)
			}
		}()
		s := factory()
		_ = s.ID()
	})
	if len(cfg.onID) > 0 {
		t.Run("ID", func(t *testing.T) {
			prePopFactory := func() crypto.Hasher {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Hasher, crypto.ID]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Hasher, crypto.ID]{
					Factory: prePopFactory,
					Call: func(impl crypto.Hasher) crypto.ID {
						return impl.ID()
					},
				},
			}
			for _, a := range cfg.onID {
				a(pctx)
			}
		})
	}
}

func runHasherNewStream(t *testing.T, factory func() crypto.Hasher, cfg *hasherConfig) {
	t.Helper()

	t.Run("NewStream/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: NewStream panicked on zero-value args (%v) — supply sample values via HasherOnNewStream", r)
			}
		}()
		s := factory()
		_ = s.NewStream()
	})
	if len(cfg.onNewStream) > 0 {
		t.Run("NewStream", func(t *testing.T) {
			prePopFactory := func() crypto.Hasher {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Hasher, crypto.Stream]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Hasher, crypto.Stream]{
					Factory: prePopFactory,
					Call: func(impl crypto.Hasher) crypto.Stream {
						return impl.NewStream()
					},
				},
			}
			for _, a := range cfg.onNewStream {
				a(pctx)
			}
		})
	}
}

// HasherOption configures [AssertHasherContract].
type HasherOption func(*hasherConfig)

// HasherPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func HasherPrePopulate(fn func(ctx context.Context, s crypto.Hasher)) HasherOption {
	return func(c *hasherConfig) { c.prePopulate = fn }
}

// HasherCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func HasherCustom(name string, fn func(*testing.T, crypto.Hasher)) HasherOption {
	return func(c *hasherConfig) {
		c.custom = append(c.custom, hasherCustomSubtest{name: name, fn: fn})
	}
}

// HasherOnAlgorithm adds plug-in assertions for the Algorithm method.
func HasherOnAlgorithm(assertions ...suite.PureAssertion[crypto.Hasher, crypto.Algorithm]) HasherOption {
	return func(c *hasherConfig) {
		c.onAlgorithm = append(c.onAlgorithm, assertions...)
	}
}

// HasherOnCombine adds plug-in assertions for the Combine method.
func HasherOnCombine(assertions ...suite.PureAssertion[crypto.Hasher, crypto.Digest]) HasherOption {
	return func(c *hasherConfig) {
		c.onCombine = append(c.onCombine, assertions...)
	}
}

// HasherOnCombineTagged adds plug-in assertions for the CombineTagged method.
func HasherOnCombineTagged(assertions ...suite.PureAssertion[crypto.Hasher, crypto.Digest]) HasherOption {
	return func(c *hasherConfig) {
		c.onCombineTagged = append(c.onCombineTagged, assertions...)
	}
}

// HasherOnHash adds plug-in assertions for the Hash method.
func HasherOnHash(assertions ...suite.PureAssertion[crypto.Hasher, crypto.Digest]) HasherOption {
	return func(c *hasherConfig) {
		c.onHash = append(c.onHash, assertions...)
	}
}

// HasherOnHashTagged adds plug-in assertions for the HashTagged method.
func HasherOnHashTagged(assertions ...suite.PureAssertion[crypto.Hasher, crypto.Digest]) HasherOption {
	return func(c *hasherConfig) {
		c.onHashTagged = append(c.onHashTagged, assertions...)
	}
}

// HasherOnID adds plug-in assertions for the ID method.
func HasherOnID(assertions ...suite.PureAssertion[crypto.Hasher, crypto.ID]) HasherOption {
	return func(c *hasherConfig) {
		c.onID = append(c.onID, assertions...)
	}
}

// HasherOnNewStream adds plug-in assertions for the NewStream method.
func HasherOnNewStream(assertions ...suite.PureAssertion[crypto.Hasher, crypto.Stream]) HasherOption {
	return func(c *hasherConfig) {
		c.onNewStream = append(c.onNewStream, assertions...)
	}
}

// HasherOnAll adds cross-method assertions that span multiple methods.
func HasherOnAll(assertions ...suite.CrossMethodAssertion[crypto.Hasher]) HasherOption {
	return func(c *hasherConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type hasherCustomSubtest struct {
	name string
	fn   func(*testing.T, crypto.Hasher)
}

type hasherConfig struct {
	prePopulate     func(context.Context, crypto.Hasher)
	custom          []hasherCustomSubtest
	onAll           []suite.CrossMethodAssertion[crypto.Hasher]
	onAlgorithm     []suite.PureAssertion[crypto.Hasher, crypto.Algorithm]
	onCombine       []suite.PureAssertion[crypto.Hasher, crypto.Digest]
	onCombineTagged []suite.PureAssertion[crypto.Hasher, crypto.Digest]
	onHash          []suite.PureAssertion[crypto.Hasher, crypto.Digest]
	onHashTagged    []suite.PureAssertion[crypto.Hasher, crypto.Digest]
	onID            []suite.PureAssertion[crypto.Hasher, crypto.ID]
	onNewStream     []suite.PureAssertion[crypto.Hasher, crypto.Stream]
}

func newHasherConfig(opts ...HasherOption) hasherConfig {
	var cfg hasherConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
