// Code generated by testkit stub. DO NOT EDIT.
// Source: hasher.go:105-161 (testkit stub Hasher)

package cryptotest

import (
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ crypto.Hasher = (*HasherStub)(nil)

// --- Call types ---

// HasherAlgorithmCall records one invocation of crypto.Hasher.Algorithm.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type HasherAlgorithmCall struct {
	Result crypto.Algorithm
}

// HasherCombineTaggedCall records one invocation of crypto.Hasher.CombineTagged.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type HasherCombineTaggedCall struct {
	R      crypto.Role
	Left   crypto.Digest
	Right  crypto.Digest
	Result crypto.Digest
}

// HasherHashCall records one invocation of crypto.Hasher.Hash.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type HasherHashCall struct {
	Data   []byte
	Result crypto.Digest
}

// HasherHashTaggedCall records one invocation of crypto.Hasher.HashTagged.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type HasherHashTaggedCall struct {
	R      crypto.Role
	Data   []byte
	Result crypto.Digest
}

// HasherIDCall records one invocation of crypto.Hasher.ID.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type HasherIDCall struct {
	Result crypto.ID
}

// HasherNewStreamCall records one invocation of crypto.Hasher.NewStream.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type HasherNewStreamCall struct {
	Result crypto.Stream
}

// --- Per-method stubs ---

// HasherAlgorithmStub controls behavior and records calls for Algorithm.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type HasherAlgorithmStub struct {
	*stub.MethodStub[HasherAlgorithmCall]
	fn       func() crypto.Algorithm
	fallback *hasherAlgorithmReturn
}

type hasherAlgorithmReturn struct {
	Result crypto.Algorithm
}

// Returns sets a fixed return value for Algorithm.
func (s *HasherAlgorithmStub) Returns(result crypto.Algorithm) *HasherAlgorithmStub {
	s.fallback = &hasherAlgorithmReturn{Result: result}
	return s
}

// Func sets a function override for Algorithm.
func (s *HasherAlgorithmStub) Func(fn func() crypto.Algorithm) *HasherAlgorithmStub {
	s.fn = fn
	return s
}

// HasherCombineTaggedStub controls behavior and records calls for CombineTagged.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type HasherCombineTaggedStub struct {
	*stub.MethodStub[HasherCombineTaggedCall]
	fn       func(crypto.Role, crypto.Digest, crypto.Digest) crypto.Digest
	fallback *hasherCombineTaggedReturn
}

type hasherCombineTaggedReturn struct {
	Result crypto.Digest
}

// Returns sets a fixed return value for CombineTagged.
func (s *HasherCombineTaggedStub) Returns(result crypto.Digest) *HasherCombineTaggedStub {
	s.fallback = &hasherCombineTaggedReturn{Result: result}
	return s
}

// Func sets a function override for CombineTagged.
func (s *HasherCombineTaggedStub) Func(fn func(crypto.Role, crypto.Digest, crypto.Digest) crypto.Digest) *HasherCombineTaggedStub {
	s.fn = fn
	return s
}

// HasherHashStub controls behavior and records calls for Hash.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type HasherHashStub struct {
	*stub.MethodStub[HasherHashCall]
	fn       func([]byte) crypto.Digest
	fallback *hasherHashReturn
}

type hasherHashReturn struct {
	Result crypto.Digest
}

// Returns sets a fixed return value for Hash.
func (s *HasherHashStub) Returns(result crypto.Digest) *HasherHashStub {
	s.fallback = &hasherHashReturn{Result: result}
	return s
}

// Func sets a function override for Hash.
func (s *HasherHashStub) Func(fn func([]byte) crypto.Digest) *HasherHashStub {
	s.fn = fn
	return s
}

// HasherHashTaggedStub controls behavior and records calls for HashTagged.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type HasherHashTaggedStub struct {
	*stub.MethodStub[HasherHashTaggedCall]
	fn       func(crypto.Role, []byte) crypto.Digest
	fallback *hasherHashTaggedReturn
}

type hasherHashTaggedReturn struct {
	Result crypto.Digest
}

// Returns sets a fixed return value for HashTagged.
func (s *HasherHashTaggedStub) Returns(result crypto.Digest) *HasherHashTaggedStub {
	s.fallback = &hasherHashTaggedReturn{Result: result}
	return s
}

// Func sets a function override for HashTagged.
func (s *HasherHashTaggedStub) Func(fn func(crypto.Role, []byte) crypto.Digest) *HasherHashTaggedStub {
	s.fn = fn
	return s
}

// HasherIDStub controls behavior and records calls for ID.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type HasherIDStub struct {
	*stub.MethodStub[HasherIDCall]
	fn       func() crypto.ID
	fallback *hasherIDReturn
}

type hasherIDReturn struct {
	Result crypto.ID
}

// Returns sets a fixed return value for ID.
func (s *HasherIDStub) Returns(result crypto.ID) *HasherIDStub {
	s.fallback = &hasherIDReturn{Result: result}
	return s
}

// Func sets a function override for ID.
func (s *HasherIDStub) Func(fn func() crypto.ID) *HasherIDStub {
	s.fn = fn
	return s
}

// HasherNewStreamStub controls behavior and records calls for NewStream.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type HasherNewStreamStub struct {
	*stub.MethodStub[HasherNewStreamCall]
	fn       func() crypto.Stream
	fallback *hasherNewStreamReturn
}

type hasherNewStreamReturn struct {
	Result crypto.Stream
}

// Returns sets a fixed return value for NewStream.
func (s *HasherNewStreamStub) Returns(result crypto.Stream) *HasherNewStreamStub {
	s.fallback = &hasherNewStreamReturn{Result: result}
	return s
}

// Func sets a function override for NewStream.
func (s *HasherNewStreamStub) Func(fn func() crypto.Stream) *HasherNewStreamStub {
	s.fn = fn
	return s
}

// --- HasherStub ---

// HasherStubOption configures a [HasherStub] at construction time.
type HasherStubOption func(*HasherStub)

// HasherStubStrict enables strict mode — unconfigured methods fail the test.
func HasherStubStrict() HasherStubOption {
	return func(s *HasherStub) { s.strict = true }
}

// HasherStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func HasherStubDelegateTo(impl crypto.Hasher) HasherStubOption {
	return func(s *HasherStub) {
		s.OnAlgorithm.Func(impl.Algorithm)
		s.OnCombineTagged.Func(impl.CombineTagged)
		s.OnHash.Func(impl.Hash)
		s.OnHashTagged.Func(impl.HashTagged)
		s.OnID.Func(impl.ID)
		s.OnNewStream.Func(impl.NewStream)
	}
}

// HasherStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func HasherStubWithClock(clk clock.Clock) HasherStubOption {
	return func(s *HasherStub) {
		s.OnAlgorithm.WithClock(clk)
		s.OnCombineTagged.WithClock(clk)
		s.OnHash.WithClock(clk)
		s.OnHashTagged.WithClock(clk)
		s.OnID.WithClock(clk)
		s.OnNewStream.WithClock(clk)
	}
}

// HasherStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func HasherStubWithRandSource(src rand.Source) HasherStubOption {
	return func(s *HasherStub) {
		s.OnAlgorithm.WithRandSource(src)
		s.OnCombineTagged.WithRandSource(src)
		s.OnHash.WithRandSource(src)
		s.OnHashTagged.WithRandSource(src)
		s.OnID.WithRandSource(src)
		s.OnNewStream.WithRandSource(src)
	}
}

// HasherStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func HasherStubBenchMode() HasherStubOption {
	return func(s *HasherStub) {
		s.OnAlgorithm.BenchMode()
		s.OnCombineTagged.BenchMode()
		s.OnHash.BenchMode()
		s.OnHashTagged.BenchMode()
		s.OnID.BenchMode()
		s.OnNewStream.BenchMode()
	}
}

// WithHasherAlgorithm sets a function override at construction time.
func WithHasherAlgorithm(fn func() crypto.Algorithm) HasherStubOption {
	return func(s *HasherStub) { s.OnAlgorithm.Func(fn) }
}

// WithHasherCombineTagged sets a function override at construction time.
func WithHasherCombineTagged(fn func(crypto.Role, crypto.Digest, crypto.Digest) crypto.Digest) HasherStubOption {
	return func(s *HasherStub) { s.OnCombineTagged.Func(fn) }
}

// WithHasherHash sets a function override at construction time.
func WithHasherHash(fn func([]byte) crypto.Digest) HasherStubOption {
	return func(s *HasherStub) { s.OnHash.Func(fn) }
}

// WithHasherHashTagged sets a function override at construction time.
func WithHasherHashTagged(fn func(crypto.Role, []byte) crypto.Digest) HasherStubOption {
	return func(s *HasherStub) { s.OnHashTagged.Func(fn) }
}

// WithHasherID sets a function override at construction time.
func WithHasherID(fn func() crypto.ID) HasherStubOption {
	return func(s *HasherStub) { s.OnID.Func(fn) }
}

// WithHasherNewStream sets a function override at construction time.
func WithHasherNewStream(fn func() crypto.Stream) HasherStubOption {
	return func(s *HasherStub) { s.OnNewStream.Func(fn) }
}

// HasherStub is a configurable test double for [crypto.Hasher].
type HasherStub struct {
	OnAlgorithm     *HasherAlgorithmStub
	OnCombineTagged *HasherCombineTaggedStub
	OnHash          *HasherHashStub
	OnHashTagged    *HasherHashTaggedStub
	OnID            *HasherIDStub
	OnNewStream     *HasherNewStreamStub
	strict          bool
}

// NewHasherStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewHasherStub(tb testing.TB, opts ...HasherStubOption) *HasherStub {
	s := &HasherStub{
		OnAlgorithm:     &HasherAlgorithmStub{MethodStub: stub.NewMethodStub[HasherAlgorithmCall](tb, "Hasher.Algorithm")},
		OnCombineTagged: &HasherCombineTaggedStub{MethodStub: stub.NewMethodStub[HasherCombineTaggedCall](tb, "Hasher.CombineTagged")},
		OnHash:          &HasherHashStub{MethodStub: stub.NewMethodStub[HasherHashCall](tb, "Hasher.Hash")},
		OnHashTagged:    &HasherHashTaggedStub{MethodStub: stub.NewMethodStub[HasherHashTaggedCall](tb, "Hasher.HashTagged")},
		OnID:            &HasherIDStub{MethodStub: stub.NewMethodStub[HasherIDCall](tb, "Hasher.ID")},
		OnNewStream:     &HasherNewStreamStub{MethodStub: stub.NewMethodStub[HasherNewStreamCall](tb, "Hasher.NewStream")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnAlgorithm.Strict()
		s.OnCombineTagged.Strict()
		s.OnHash.Strict()
		s.OnHashTagged.Strict()
		s.OnID.Strict()
		s.OnNewStream.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnAlgorithm.Verify()
				s.OnCombineTagged.Verify()
				s.OnHash.Verify()
				s.OnHashTagged.Verify()
				s.OnID.Verify()
				s.OnNewStream.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *HasherStub) ResetCalls() {
	s.OnAlgorithm.Reset()
	s.OnCombineTagged.Reset()
	s.OnHash.Reset()
	s.OnHashTagged.Reset()
	s.OnID.Reset()
	s.OnNewStream.Reset()
}

// --- Interface method implementations ---

func (s *HasherStub) Algorithm() crypto.Algorithm {
	s.OnAlgorithm.SleepLatency()
	call := HasherAlgorithmCall{}
	if s.OnAlgorithm.fn != nil {
		r0 := s.OnAlgorithm.fn()
		call.Result = r0
		s.OnAlgorithm.Record(call)
		return r0
	}
	if s.OnAlgorithm.fallback != nil {
		f := s.OnAlgorithm.fallback
		call.Result = f.Result
		s.OnAlgorithm.Record(call)
		return f.Result
	}
	s.OnAlgorithm.FailUnexpectedCall(call)
	s.OnAlgorithm.Record(call)
	return ""
}

func (s *HasherStub) CombineTagged(r crypto.Role, left crypto.Digest, right crypto.Digest) crypto.Digest {
	s.OnCombineTagged.SleepLatency()
	call := HasherCombineTaggedCall{R: r, Left: left, Right: right}
	if s.OnCombineTagged.fn != nil {
		r0 := s.OnCombineTagged.fn(r, left, right)
		call.Result = r0
		s.OnCombineTagged.Record(call)
		return r0
	}
	if s.OnCombineTagged.fallback != nil {
		f := s.OnCombineTagged.fallback
		call.Result = f.Result
		s.OnCombineTagged.Record(call)
		return f.Result
	}
	s.OnCombineTagged.FailUnexpectedCall(call)
	s.OnCombineTagged.Record(call)
	return crypto.Digest{}
}

func (s *HasherStub) Hash(data []byte) crypto.Digest {
	s.OnHash.SleepLatency()
	call := HasherHashCall{Data: data}
	if s.OnHash.fn != nil {
		r0 := s.OnHash.fn(data)
		call.Result = r0
		s.OnHash.Record(call)
		return r0
	}
	if s.OnHash.fallback != nil {
		f := s.OnHash.fallback
		call.Result = f.Result
		s.OnHash.Record(call)
		return f.Result
	}
	s.OnHash.FailUnexpectedCall(call)
	s.OnHash.Record(call)
	return crypto.Digest{}
}

func (s *HasherStub) HashTagged(r crypto.Role, data []byte) crypto.Digest {
	s.OnHashTagged.SleepLatency()
	call := HasherHashTaggedCall{R: r, Data: data}
	if s.OnHashTagged.fn != nil {
		r0 := s.OnHashTagged.fn(r, data)
		call.Result = r0
		s.OnHashTagged.Record(call)
		return r0
	}
	if s.OnHashTagged.fallback != nil {
		f := s.OnHashTagged.fallback
		call.Result = f.Result
		s.OnHashTagged.Record(call)
		return f.Result
	}
	s.OnHashTagged.FailUnexpectedCall(call)
	s.OnHashTagged.Record(call)
	return crypto.Digest{}
}

func (s *HasherStub) ID() crypto.ID {
	s.OnID.SleepLatency()
	call := HasherIDCall{}
	if s.OnID.fn != nil {
		r0 := s.OnID.fn()
		call.Result = r0
		s.OnID.Record(call)
		return r0
	}
	if s.OnID.fallback != nil {
		f := s.OnID.fallback
		call.Result = f.Result
		s.OnID.Record(call)
		return f.Result
	}
	s.OnID.FailUnexpectedCall(call)
	s.OnID.Record(call)
	return crypto.ID{}
}

func (s *HasherStub) NewStream() crypto.Stream {
	s.OnNewStream.SleepLatency()
	call := HasherNewStreamCall{}
	if s.OnNewStream.fn != nil {
		r0 := s.OnNewStream.fn()
		call.Result = r0
		s.OnNewStream.Record(call)
		return r0
	}
	if s.OnNewStream.fallback != nil {
		f := s.OnNewStream.fallback
		call.Result = f.Result
		s.OnNewStream.Record(call)
		return f.Result
	}
	s.OnNewStream.FailUnexpectedCall(call)
	s.OnNewStream.Record(call)
	return nil
}
