// Code generated by testkit model. DO NOT EDIT.
// Source: hasher.go:105-161 (testkit model Hasher)

package cryptotest

import (
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit/model"
	"go.thesmos.sh/testkit/model/action"
	"go.thesmos.sh/testkit/model/law"
)

// AssertHasherModel runs property-based state-machine tests against
// implementations of [crypto.Hasher] produced by sutFactory.
//
//	Shapes:        Pure (Algorithm, CombineTagged, Hash, HashTagged, ID, NewStream)
//	CRUD:          no
//	Key field:     none
//	Ref:           supply via HasherModelReference (Algorithm, CombineTagged, Hash, HashTagged, ID, NewStream not in MapStore)
//	Auto-laws:     AUTO-PURE-DETERMINISTIC
//	Chain:         none
//	Skipped:       none
//	Concurrent:    not emitted (interface lacks Reader+Writer/Deleter for Porcupine; use manual model.WithConcurrent + StressActions)
//	Plug-in:       HasherModelReference, HasherModelActions, HasherModelLaw, HasherModelSkipLaw
func AssertHasherModel(
	t model.TB,
	sutFactory func() crypto.Hasher,
	opts ...HasherModelOption,
) {
	t.Helper()
	cfg := newHasherModelConfig(opts...)
	if cfg.leakCheck {
		artifactDir := model.ResolveArtifactDir(cfg.artifactDir)
		model.CheckGoroutineLeaks(t, artifactDir, func() {
			model.Check(t, HasherModelProperty(sutFactory, opts...))
		})
		return
	}
	model.Check(t, HasherModelProperty(sutFactory, opts...))
}

// TestHasherModel runs the model property as a standalone test.
// Equivalent to AssertHasherModel but takes *testing.T directly
// and skips leak checking and concurrent dispatch. Use when you need
// the property function for both Test and Fuzz targets with shared options:
//
//	opts := []HasherModelOption{...}
//	func TestFoo(t *testing.T)  { HasherModelTest(t, factory, opts...) }
//	func FuzzFoo(f *testing.F)  { HasherModelFuzz(f, factory, opts...) }
func HasherModelTest(
	t *testing.T,
	sutFactory func() crypto.Hasher,
	opts ...HasherModelOption,
) {
	t.Helper()
	model.Check(t, HasherModelProperty(sutFactory, opts...))
}

// HasherModelFuzz is the fuzz counterpart of [HasherModelTest].
// Same property, coverage-guided via go test -fuzz.
func HasherModelFuzz(
	f *testing.F,
	sutFactory func() crypto.Hasher,
	opts ...HasherModelOption,
) {
	f.Helper()
	f.Fuzz(model.MakeFuzz(HasherModelProperty(sutFactory, opts...)))
}

// FuzzHasherModel is a fuzz target for coverage-guided testing
// of [crypto.Hasher] via go test -fuzz.
func FuzzHasherModel(
	f *testing.F,
	sutFactory func() crypto.Hasher,
	opts ...HasherModelOption,
) {
	f.Helper()
	f.Fuzz(model.MakeFuzz(HasherModelProperty(sutFactory, opts...)))
}

// HasherModelProperty builds the rapid property function.
// Use directly for shared model.Check / model.MakeFuzz targets:
//
//	prop := HasherModelProperty(factory, opts...)
//	model.Check(t, prop)                    // test
//	f.Fuzz(model.MakeFuzz(prop))            // fuzz
func HasherModelProperty(
	sutFactory func() crypto.Hasher,
	opts ...HasherModelOption,
) func(*model.T) {
	cfg := newHasherModelConfig(opts...)

	// Generators — local to this function, not package-level.

	// Reference: consumer-supplied or synthesized.
	refFactory := cfg.refFactory

	// Actions: consumer-supplied or auto-derived.
	actions := cfg.actions
	if len(actions) == 0 {
		actions = []model.Action[crypto.Hasher]{
			action.Pure("Algorithm",
				func(impl crypto.Hasher) crypto.Algorithm {
					return impl.Algorithm()
				},
			),
			action.Pure("ID",
				func(impl crypto.Hasher) crypto.ID {
					return impl.ID()
				},
			),
			action.Stress("NewStream", func(impl crypto.Hasher) { impl.NewStream() }),
		}
	}
	actions = append(actions, cfg.extraActions...)

	// Laws: auto-derived + consumer-supplied.
	laws := model.NewRegistry[crypto.Hasher]()
	laws.Add(law.PureDeterminism[crypto.Hasher, crypto.Algorithm]{
		Call: func(rt *model.T, impl crypto.Hasher) crypto.Algorithm {
			return impl.Algorithm()
		},
	})
	laws.Add(law.PureDeterminism[crypto.Hasher, crypto.ID]{
		Call: func(rt *model.T, impl crypto.Hasher) crypto.ID {
			return impl.ID()
		},
	})
	for _, l := range cfg.laws {
		laws.Add(l)
	}
	for _, id := range cfg.skipLaws {
		laws.SkipByID(id)
	}

	modelOpts := []model.Option[crypto.Hasher]{
		model.WithReference(refFactory),
		model.WithActions(actions...),
		model.WithLaws(laws),
	}
	if cfg.disableTrace {
		modelOpts = append(modelOpts, model.WithoutTrace[crypto.Hasher]())
	}
	if cfg.artifactDir != "" {
		modelOpts = append(modelOpts, model.WithArtifactDir[crypto.Hasher](cfg.artifactDir))
	}
	return model.Property(sutFactory, modelOpts...)
}

// HasherModelOption configures [AssertHasherModel].
type HasherModelOption func(*hasherModelConfig)

// HasherModelReference overrides the auto-synthesized reference
// with a consumer-supplied implementation.
func HasherModelReference(factory func() crypto.Hasher) HasherModelOption {
	return func(c *hasherModelConfig) { c.refFactory = factory }
}

// HasherModelActions replaces all auto-derived actions.
func HasherModelActions(actions ...model.Action[crypto.Hasher]) HasherModelOption {
	return func(c *hasherModelConfig) { c.actions = actions }
}

// HasherModelExtraActions appends actions to the auto-derived set.
func HasherModelExtraActions(actions ...model.Action[crypto.Hasher]) HasherModelOption {
	return func(c *hasherModelConfig) { c.extraActions = append(c.extraActions, actions...) }
}

// HasherModelLaw adds a custom law to the registry.
func HasherModelLaw(l law.Law[crypto.Hasher]) HasherModelOption {
	return func(c *hasherModelConfig) { c.laws = append(c.laws, l) }
}

// HasherModelSkipLaw skips an auto-derived law by ID.
func HasherModelSkipLaw(id string) HasherModelOption {
	return func(c *hasherModelConfig) { c.skipLaws = append(c.skipLaws, id) }
}

// HasherModelWithoutTrace disables per-action trace recording.
func HasherModelWithoutTrace() HasherModelOption {
	return func(c *hasherModelConfig) { c.disableTrace = true }
}

// HasherModelArtifactDir overrides the directory for failure artifacts.
func HasherModelArtifactDir(dir string) HasherModelOption {
	return func(c *hasherModelConfig) { c.artifactDir = dir }
}

// HasherModelGoroutineLeakCheck enables goroutine leak detection
// at iteration end via stack-based ID diffing.
func HasherModelGoroutineLeakCheck() HasherModelOption {
	return func(c *hasherModelConfig) { c.leakCheck = true }
}

type hasherModelConfig struct {
	refFactory   func() crypto.Hasher
	actions      []model.Action[crypto.Hasher]
	extraActions []model.Action[crypto.Hasher]
	laws         []law.Law[crypto.Hasher]
	skipLaws     []string
	disableTrace bool
	artifactDir  string
	leakCheck    bool
}

func newHasherModelConfig(opts ...HasherModelOption) hasherModelConfig {
	var cfg hasherModelConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
