// Code generated by testkit stub. DO NOT EDIT.
// Source: hasher.go:105-161 (testkit stub Hasher)

package cryptotest_test

import (
	"testing"

	"go.thesmos.sh/core/coretest/cryptotest"
	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/rand"
)

func TestHasherStub(t *testing.T) {
	t.Parallel()

	t.Run("Algorithm default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		result := s.Algorithm()
		testkit.Equal(t, result, "", "Algorithm must return zero")
	})

	t.Run("Algorithm Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		called := false
		s.OnAlgorithm.Func(func() crypto.Algorithm {
			called = true
			return crypto.Algorithm("test-result")
		})
		result := s.Algorithm()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Func must return set value")
	})

	t.Run("Algorithm Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Returns must return set value")
	})

	t.Run("Algorithm records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.Algorithm()
		s.OnAlgorithm.AssertCalledOnce(t, "must record Algorithm call")
	})

	t.Run("WithHasherAlgorithm constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewHasherStub(t, cryptotest.WithHasherAlgorithm(func() crypto.Algorithm {
			called = true
			return ""
		}))
		_ = s.Algorithm()
		testkit.True(t, called, "WithHasherAlgorithm must be called")
	})

	t.Run("Algorithm OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		var observed []cryptotest.HasherAlgorithmCall
		s.OnAlgorithm.OnRecord(func(c cryptotest.HasherAlgorithmCall) {
			observed = append(observed, c)
		})
		_ = s.Algorithm()
		_ = s.Algorithm()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Algorithm call")
	})

	t.Run("CombineTagged default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		result := s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.Equal(t, result, crypto.Digest{}, "CombineTagged must return zero")
	})

	t.Run("CombineTagged Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		called := false
		s.OnCombineTagged.Func(func(crypto.Role, crypto.Digest, crypto.Digest) crypto.Digest {
			called = true
			return crypto.Digest{}
		})
		result := s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, crypto.Digest{}, "Func must return set value")
	})

	t.Run("CombineTagged Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnCombineTagged.Returns(crypto.Digest{})
		result := s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.Equal(t, result, crypto.Digest{}, "Returns must return set value")
	})

	t.Run("CombineTagged records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		s.OnCombineTagged.AssertCalledOnce(t, "must record CombineTagged call")
	})

	t.Run("WithHasherCombineTagged constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewHasherStub(t, cryptotest.WithHasherCombineTagged(func(crypto.Role, crypto.Digest, crypto.Digest) crypto.Digest {
			called = true
			return crypto.Digest{}
		}))
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.True(t, called, "WithHasherCombineTagged must be called")
	})

	t.Run("CombineTagged records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.CombineTagged(crypto.Role(42), crypto.Digest{}, crypto.Digest{})
		call := s.OnCombineTagged.LastCall(t)
		testkit.Equal(t, call.R, crypto.Role(42), "R must be recorded")
		testkit.Equal(t, call.Left, crypto.Digest{}, "Left must be recorded")
		testkit.Equal(t, call.Right, crypto.Digest{}, "Right must be recorded")
	})

	t.Run("CombineTagged OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		var observed []cryptotest.HasherCombineTaggedCall
		s.OnCombineTagged.OnRecord(func(c cryptotest.HasherCombineTaggedCall) {
			observed = append(observed, c)
		})
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every CombineTagged call")
	})

	t.Run("Hash default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		result := s.Hash(nil)
		testkit.Equal(t, result, crypto.Digest{}, "Hash must return zero")
	})

	t.Run("Hash Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		called := false
		s.OnHash.Func(func([]byte) crypto.Digest {
			called = true
			return crypto.Digest{}
		})
		result := s.Hash(nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, crypto.Digest{}, "Func must return set value")
	})

	t.Run("Hash Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnHash.Returns(crypto.Digest{})
		result := s.Hash(nil)
		testkit.Equal(t, result, crypto.Digest{}, "Returns must return set value")
	})

	t.Run("Hash records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.Hash(nil)
		s.OnHash.AssertCalledOnce(t, "must record Hash call")
	})

	t.Run("WithHasherHash constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewHasherStub(t, cryptotest.WithHasherHash(func([]byte) crypto.Digest {
			called = true
			return crypto.Digest{}
		}))
		_ = s.Hash(nil)
		testkit.True(t, called, "WithHasherHash must be called")
	})

	t.Run("Hash records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.Hash([]byte{42})
		call := s.OnHash.LastCall(t)
		testkit.Equal(t, call.Data, []byte{42}, "Data must be recorded")
	})

	t.Run("Hash OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		var observed []cryptotest.HasherHashCall
		s.OnHash.OnRecord(func(c cryptotest.HasherHashCall) {
			observed = append(observed, c)
		})
		_ = s.Hash(nil)
		_ = s.Hash(nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Hash call")
	})

	t.Run("HashTagged default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		result := s.HashTagged(0, nil)
		testkit.Equal(t, result, crypto.Digest{}, "HashTagged must return zero")
	})

	t.Run("HashTagged Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		called := false
		s.OnHashTagged.Func(func(crypto.Role, []byte) crypto.Digest {
			called = true
			return crypto.Digest{}
		})
		result := s.HashTagged(0, nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, crypto.Digest{}, "Func must return set value")
	})

	t.Run("HashTagged Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnHashTagged.Returns(crypto.Digest{})
		result := s.HashTagged(0, nil)
		testkit.Equal(t, result, crypto.Digest{}, "Returns must return set value")
	})

	t.Run("HashTagged records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.HashTagged(0, nil)
		s.OnHashTagged.AssertCalledOnce(t, "must record HashTagged call")
	})

	t.Run("WithHasherHashTagged constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewHasherStub(t, cryptotest.WithHasherHashTagged(func(crypto.Role, []byte) crypto.Digest {
			called = true
			return crypto.Digest{}
		}))
		_ = s.HashTagged(0, nil)
		testkit.True(t, called, "WithHasherHashTagged must be called")
	})

	t.Run("HashTagged records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.HashTagged(crypto.Role(42), []byte{42})
		call := s.OnHashTagged.LastCall(t)
		testkit.Equal(t, call.R, crypto.Role(42), "R must be recorded")
		testkit.Equal(t, call.Data, []byte{42}, "Data must be recorded")
	})

	t.Run("HashTagged OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		var observed []cryptotest.HasherHashTaggedCall
		s.OnHashTagged.OnRecord(func(c cryptotest.HasherHashTaggedCall) {
			observed = append(observed, c)
		})
		_ = s.HashTagged(0, nil)
		_ = s.HashTagged(0, nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every HashTagged call")
	})

	t.Run("ID default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		result := s.ID()
		testkit.Equal(t, result, crypto.ID{}, "ID must return zero")
	})

	t.Run("ID Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		called := false
		s.OnID.Func(func() crypto.ID {
			called = true
			return [16]byte{1}
		})
		result := s.ID()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, [16]byte{1}, "Func must return set value")
	})

	t.Run("ID Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnID.Returns([16]byte{1})
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "Returns must return set value")
	})

	t.Run("ID records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.ID()
		s.OnID.AssertCalledOnce(t, "must record ID call")
	})

	t.Run("WithHasherID constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewHasherStub(t, cryptotest.WithHasherID(func() crypto.ID {
			called = true
			return crypto.ID{}
		}))
		_ = s.ID()
		testkit.True(t, called, "WithHasherID must be called")
	})

	t.Run("ID OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		var observed []cryptotest.HasherIDCall
		s.OnID.OnRecord(func(c cryptotest.HasherIDCall) {
			observed = append(observed, c)
		})
		_ = s.ID()
		_ = s.ID()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every ID call")
	})

	t.Run("NewStream default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		result := s.NewStream()
		testkit.Equal(t, result, nil, "NewStream must return zero")
	})

	t.Run("NewStream Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		called := false
		s.OnNewStream.Func(func() crypto.Stream {
			called = true
			return nil
		})
		result := s.NewStream()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("NewStream Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnNewStream.Returns(nil)
		result := s.NewStream()
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("NewStream records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.NewStream()
		s.OnNewStream.AssertCalledOnce(t, "must record NewStream call")
	})

	t.Run("WithHasherNewStream constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewHasherStub(t, cryptotest.WithHasherNewStream(func() crypto.Stream {
			called = true
			return nil
		}))
		_ = s.NewStream()
		testkit.True(t, called, "WithHasherNewStream must be called")
	})

	t.Run("NewStream OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		var observed []cryptotest.HasherNewStreamCall
		s.OnNewStream.OnRecord(func(c cryptotest.HasherNewStreamCall) {
			observed = append(observed, c)
		})
		_ = s.NewStream()
		_ = s.NewStream()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every NewStream call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubBenchMode())
		_ = s.Algorithm()
		testkit.Equal(t, s.OnAlgorithm.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f)
		s.OnAlgorithm.Times(2)
		_ = s.Algorithm()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f)
		s.OnAlgorithm.TimesAtLeast(3)
		_ = s.Algorithm()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.Algorithm()
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		_ = s.Hash(nil)
		_ = s.HashTagged(0, nil)
		_ = s.ID()
		_ = s.NewStream()
		s.ResetCalls()
		s.OnAlgorithm.AssertNotCalled(t, "Algorithm must be cleared after ResetCalls")
		s.OnCombineTagged.AssertNotCalled(t, "CombineTagged must be cleared after ResetCalls")
		s.OnHash.AssertNotCalled(t, "Hash must be cleared after ResetCalls")
		s.OnHashTagged.AssertNotCalled(t, "HashTagged must be cleared after ResetCalls")
		s.OnID.AssertNotCalled(t, "ID must be cleared after ResetCalls")
		s.OnNewStream.AssertNotCalled(t, "NewStream must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Algorithm", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f, cryptotest.HasherStubStrict())
		_ = s.Algorithm()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Algorithm")
	})

	t.Run("Strict mode fails on unconfigured CombineTagged", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f, cryptotest.HasherStubStrict())
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured CombineTagged")
	})

	t.Run("Strict mode fails on unconfigured Hash", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f, cryptotest.HasherStubStrict())
		_ = s.Hash(nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Hash")
	})

	t.Run("Strict mode fails on unconfigured HashTagged", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f, cryptotest.HasherStubStrict())
		_ = s.HashTagged(0, nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured HashTagged")
	})

	t.Run("Strict mode fails on unconfigured ID", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f, cryptotest.HasherStubStrict())
		_ = s.ID()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured ID")
	})

	t.Run("Strict mode fails on unconfigured NewStream", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewHasherStub(f, cryptotest.HasherStubStrict())
		_ = s.NewStream()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured NewStream")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewHasherStub(t)
		inner.OnAlgorithm.Returns("")
		inner.OnCombineTagged.Returns(crypto.Digest{})
		inner.OnHash.Returns(crypto.Digest{})
		inner.OnHashTagged.Returns(crypto.Digest{})
		inner.OnID.Returns(crypto.ID{})
		inner.OnNewStream.Returns(nil)
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubDelegateTo(inner))
		_ = s.Algorithm()
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		_ = s.Hash(nil)
		_ = s.HashTagged(0, nil)
		_ = s.ID()
		_ = s.NewStream()
		s.OnAlgorithm.AssertCalledOnce(t, "Algorithm must delegate")
		s.OnCombineTagged.AssertCalledOnce(t, "CombineTagged must delegate")
		s.OnHash.AssertCalledOnce(t, "Hash must delegate")
		s.OnHashTagged.AssertCalledOnce(t, "HashTagged must delegate")
		s.OnID.AssertCalledOnce(t, "ID must delegate")
		s.OnNewStream.AssertCalledOnce(t, "NewStream must delegate")
	})

	t.Run("DelegateTo surfaces Algorithm return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewHasherStub(t)
		inner.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubDelegateTo(inner))
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Algorithm must return configured value")
	})

	t.Run("DelegateTo surfaces CombineTagged return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewHasherStub(t)
		inner.OnCombineTagged.Returns(crypto.Digest{})
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubDelegateTo(inner))
		result := s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.Equal(t, result, crypto.Digest{}, "CombineTagged must return configured value")
	})

	t.Run("DelegateTo surfaces Hash return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewHasherStub(t)
		inner.OnHash.Returns(crypto.Digest{})
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubDelegateTo(inner))
		result := s.Hash(nil)
		testkit.Equal(t, result, crypto.Digest{}, "Hash must return configured value")
	})

	t.Run("DelegateTo surfaces HashTagged return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewHasherStub(t)
		inner.OnHashTagged.Returns(crypto.Digest{})
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubDelegateTo(inner))
		result := s.HashTagged(0, nil)
		testkit.Equal(t, result, crypto.Digest{}, "HashTagged must return configured value")
	})

	t.Run("DelegateTo surfaces ID return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewHasherStub(t)
		inner.OnID.Returns([16]byte{1})
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubDelegateTo(inner))
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "ID must return configured value")
	})

	t.Run("DelegateTo surfaces NewStream return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewHasherStub(t)
		inner.OnNewStream.Returns(nil)
		s := cryptotest.NewHasherStub(t, cryptotest.HasherStubDelegateTo(inner))
		result := s.NewStream()
		testkit.Equal(t, result, nil, "NewStream must return configured value")
	})

	t.Run("ResetCalls preserves Algorithm Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		_ = s.Algorithm()
		s.ResetCalls()
		s.OnAlgorithm.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Algorithm must return configured value")
	})

	t.Run("ResetCalls preserves CombineTagged Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnCombineTagged.Returns(crypto.Digest{})
		_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		s.ResetCalls()
		s.OnCombineTagged.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		testkit.Equal(t, result, crypto.Digest{}, "CombineTagged must return configured value")
	})

	t.Run("ResetCalls preserves Hash Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnHash.Returns(crypto.Digest{})
		_ = s.Hash(nil)
		s.ResetCalls()
		s.OnHash.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Hash(nil)
		testkit.Equal(t, result, crypto.Digest{}, "Hash must return configured value")
	})

	t.Run("ResetCalls preserves HashTagged Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnHashTagged.Returns(crypto.Digest{})
		_ = s.HashTagged(0, nil)
		s.ResetCalls()
		s.OnHashTagged.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.HashTagged(0, nil)
		testkit.Equal(t, result, crypto.Digest{}, "HashTagged must return configured value")
	})

	t.Run("ResetCalls preserves ID Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnID.Returns([16]byte{1})
		_ = s.ID()
		s.ResetCalls()
		s.OnID.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "ID must return configured value")
	})

	t.Run("ResetCalls preserves NewStream Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		s.OnNewStream.Returns(nil)
		_ = s.NewStream()
		s.ResetCalls()
		s.OnNewStream.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.NewStream()
		testkit.Equal(t, result, nil, "NewStream must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewHasherStub(t)
		_ = s.Algorithm()
		testkit.Len(t, s.OnAlgorithm.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnAlgorithm.Timestamped(), 0, "ResetCalls must clear timestamps")
	})
}

func TestHasherStubBenchModeZeroAlloc(t *testing.T) {
	s := cryptotest.NewHasherStub(nil, cryptotest.HasherStubBenchMode())
	s.OnAlgorithm.Returns("")
	s.OnCombineTagged.Returns(crypto.Digest{})
	s.OnHash.Returns(crypto.Digest{})
	s.OnHashTagged.Returns(crypto.Digest{})
	s.OnID.Returns(crypto.ID{})
	s.OnNewStream.Returns(nil)

	t.Run("Algorithm", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Algorithm()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Algorithm in BenchMode must be 0 alloc")
	})

	t.Run("CombineTagged", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.CombineTagged(0, crypto.Digest{}, crypto.Digest{})
		})
		testkit.Equal(t, int(avgAllocs), 0, "CombineTagged in BenchMode must be 0 alloc")
	})

	t.Run("Hash", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Hash(nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Hash in BenchMode must be 0 alloc")
	})

	t.Run("HashTagged", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.HashTagged(0, nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "HashTagged in BenchMode must be 0 alloc")
	})

	t.Run("ID", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.ID()
		})
		testkit.Equal(t, int(avgAllocs), 0, "ID in BenchMode must be 0 alloc")
	})

	t.Run("NewStream", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.NewStream()
		})
		testkit.Equal(t, int(avgAllocs), 0, "NewStream in BenchMode must be 0 alloc")
	})

}
